name: Publish Docker

on:
  push:
      branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        registry: docker.pkg.github.com
        name: docker.pkg.github.com/DivisionBell2/top-app/top-app
        username: ${{ secrets.DOCKER_USERNAME }}
        # token in secrets
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "develop"
